# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_location',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
