# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='images/')),
                ('image_name', models.CharField(max_length=30)),
                ('image_caption', models.CharField(max_length=30)),
                ('posted_time', models.DateTimeField(auto_now_add=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta.Profile')),
            ],
            options={
                'ordering': ['-posted_time'],
            },
        ),
    ]
